spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/office_attendance
    username: postgres
    password: postgres

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
